name: HTML Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t html-app .

      - name: Run Docker container
        run: |
          docker rm -f html-app || true
          docker run -d -p 8080:80 html-app
